package academy.devdojo.maratonajava.javacore.Hheranca.Test;

import academy.devdojo.maratonajava.javacore.Hheranca.dominio.Funcionario;

public class HerancaTest02 {
    //0 - BLOCO DE INICIALIZAÇAO ESTATICO DA SUPER CLASSE É EXECUTADO QUANDO A JVM CARREGAR A CLASSE PAI
    //1 - BLOCO DE INICIALIZAÇAO ESTATICO DA SUPER CLASSE É EXECUTADO QUANDO A JVM CARREGAR A CLASSE FILHA
    //2 - ALOCADO ESPACO EM MEMORIA PARA O OBJETO DA SUPERCLASSE PAI
    //3 - CADA ATRIBUTO DE SUPERCLASSE PAI É CRIADO E INICIALIZADO COM VALORES DEFAULT OU O QUE FOR PASSADO
    //4 - O BLOCO DE INICIALIZACAO DA SUPER CLASSE É EXECUTADO NA ORDEM EM QUE APARECE
    //5 - O CONSTRUTOR É EXECUTADO DA SUPERCLASSE
    //6 - ALOCADO ESPACO EM MEMORIA PARA O OBJETO DA SUBCLASSE
    //3 - CADA ATRIBUTO DE SUBCLASSE PAI É CRIADO E INICIALIZADO COM VALORES DEFAULT OU O QUE FOR PASSADO
    //4 - O BLOCO DE INICIALIZACAO DA SUBCLASSE  É EXECUTADO NA ORDEM EM QUE APARECE
    //5 - O CONSTRUTOR É EXECUTADO DA SUBCLASSE
    public static void main(String[] args) {
        Funcionario funcionario = new Funcionario("Jiraya");
    }
}
